services:
  tiendaservicios.api.author:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapiauthor
    build:
      context: .
      dockerfile: TiendaServicios.Api.Author/Dockerfile
  tiendaservicios.api.book:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapibook
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libro/Dockerfile

  tiendaservicios.api.gateway:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapigateway
    build:
      context: .
      dockerfile: TiendaServicios.Api.Gateway/Dockerfile

networks:
  default:
    external:
        name: microservicenet



